name: Node.js Package

on: push

jobs:
  publish-bytesafe:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 12
          registry-url: https://gprzybylowicz.bytesafe.dev/r/test/
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.BYTESAFE_NPM_TOKEN}}
